import type { FormSection } from "../primitives";

// Plataformas de redes sociais — subset comum + "NENHUMA" no topo.
const SOCIAL_PLATFORMS = [
  { value: "NONE", label: "Nenhuma" },
  { value: "FCBK", label: "Facebook" },
  { value: "INST", label: "Instagram" },
  { value: "TWIT", label: "Twitter / X" },
  { value: "LINK", label: "LinkedIn" },
  { value: "YTUB", label: "YouTube" },
  { value: "TUMB", label: "Tumblr" },
  { value: "FLKR", label: "Flickr" },
  { value: "PTST", label: "Pinterest" },
  { value: "RDDT", label: "Reddit" },
  { value: "VKON", label: "VKontakte" },
  { value: "ASKF", label: "Ask.fm" },
  { value: "MYSP", label: "MySpace" },
  { value: "GOGL", label: "Google+" },
];

export const addressPhoneSection: FormSection = {
  id: "addressPhone",
  label: "Endereço e Telefone",
  fields: [
    // --- Endereço Residencial ---
    { id: "homeHeading", type: "heading", label: "Endereço residencial" },
    {
      id: "homeCountry",
      type: "select",
      label: "País / Região",
      required: true,
      optionsRef: "countries",
      default: "BRZL",
      ds160: "ddlCountry",
    },
    {
      id: "homePostalCode",
      type: "text",
      label: "CEP / Código Postal",
      required: true,
      maxLen: 10,
      allowNA: true,
      hint: "Ao digitar CEP brasileiro de 8 dígitos, completamos rua/cidade/estado automaticamente.",
      ds160: "tbxAPP_ADDR_POSTAL_CD",
    },
    {
      id: "homeStreet1",
      type: "text",
      label: "Rua / Endereço — Linha 1",
      required: true,
      maxLen: 40,
      ds160: "tbxAPP_ADDR_LN1",
    },
    {
      id: "homeStreet2",
      type: "text",
      label: "Rua / Endereço — Linha 2",
      maxLen: 40,
      ds160: "tbxAPP_ADDR_LN2",
    },
    {
      id: "homeCity",
      type: "text",
      label: "Cidade",
      required: true,
      maxLen: 20,
      noSpecial: true,
      ds160: "tbxAPP_ADDR_CITY",
    },
    {
      id: "homeState",
      type: "text",
      label: "Estado / Província",
      required: true,
      maxLen: 20,
      noSpecial: true,
      allowNA: true,
      ds160: "tbxAPP_ADDR_STATE",
    },

    // --- Endereço para Correspondência ---
    { id: "mailHeading", type: "heading", label: "Endereço para correspondência" },
    {
      id: "mailingAddressSame",
      type: "radio",
      label: "Mesmo endereço residencial?",
      required: true,
      ds160: "rblMailingAddrSame",
    },
    {
      id: "mailCountry",
      type: "select",
      label: "País / Região",
      required: true,
      optionsRef: "countries",
      showWhen: { field: "mailingAddressSame", equals: "N" },
      ds160: "ddlMailCountry",
    },
    {
      id: "mailPostalCode",
      type: "text",
      label: "CEP / Código Postal",
      required: true,
      maxLen: 10,
      allowNA: true,
      showWhen: { field: "mailingAddressSame", equals: "N" },
      ds160: "tbxMAILING_ADDR_POSTAL_CD",
    },
    {
      id: "mailStreet1",
      type: "text",
      label: "Rua / Endereço — Linha 1",
      required: true,
      maxLen: 40,
      showWhen: { field: "mailingAddressSame", equals: "N" },
      ds160: "tbxMAILING_ADDR_LN1",
    },
    {
      id: "mailStreet2",
      type: "text",
      label: "Rua / Endereço — Linha 2",
      maxLen: 40,
      showWhen: { field: "mailingAddressSame", equals: "N" },
      ds160: "tbxMAILING_ADDR_LN2",
    },
    {
      id: "mailCity",
      type: "text",
      label: "Cidade",
      required: true,
      maxLen: 20,
      showWhen: { field: "mailingAddressSame", equals: "N" },
      ds160: "tbxMAILING_ADDR_CITY",
    },
    {
      id: "mailState",
      type: "text",
      label: "Estado / Província",
      required: true,
      maxLen: 20,
      allowNA: true,
      showWhen: { field: "mailingAddressSame", equals: "N" },
      ds160: "tbxMAILING_ADDR_STATE",
    },

    // --- Telefones ---
    { id: "phoneHeading", type: "heading", label: "Telefones" },
    {
      id: "phone",
      type: "phone",
      label: "Telefone principal",
      required: true,
      hint: "Fixo ou celular de mais fácil acesso.",
      phoneCountry: "br",
      ds160: "tbxAPP_HOME_TEL",
    },
    {
      id: "mobilePhone",
      type: "phone",
      label: "Telefone secundário",
      allowNA: true,
      phoneCountry: "br",
      ds160: "tbxAPP_MOBILE_TEL",
    },
    {
      id: "businessPhone",
      type: "phone",
      label: "Telefone comercial",
      allowNA: true,
      phoneCountry: "br",
      ds160: "tbxAPP_BUS_TEL",
    },
    {
      id: "additionalPhones",
      type: "radio",
      label: "Usou outros telefones nos últimos 5 anos?",
      required: true,
      ds160: "rblAddPhone",
    },
    {
      id: "additionalPhoneNumbers",
      type: "array",
      label: "Telefones adicionais",
      maxItems: 4,
      showWhen: { field: "additionalPhones", equals: "Y" },
      fields: [
        {
          id: "phone",
          type: "phone",
          label: "Telefone",
          required: true,
          phoneCountry: "br",
        },
      ],
    },

    // --- Emails ---
    { id: "emailHeading", type: "heading", label: "Emails" },
    {
      id: "email",
      type: "email",
      label: "Email principal",
      required: true,
      maxLen: 50,
      hint: "Email que você acessa com frequência.",
      ds160: "tbxAPP_EMAIL_ADDR",
    },
    {
      id: "additionalEmails",
      type: "radio",
      label: "Usou outros emails nos últimos 5 anos?",
      required: true,
      ds160: "rblAddEmail",
    },
    {
      id: "additionalEmailAddresses",
      type: "array",
      label: "Emails adicionais",
      maxItems: 4,
      showWhen: { field: "additionalEmails", equals: "Y" },
      fields: [
        {
          id: "email",
          type: "email",
          label: "Email",
          required: true,
          maxLen: 50,
        },
      ],
    },

    // --- Redes Sociais ---
    {
      id: "_socialMediaIntro",
      type: "orientation",
      text:
        "Liste as redes sociais onde mantém presença nos últimos 5 anos. Marque \"Nenhuma\" na primeira entrada se não usa nenhuma — essa opção bloqueia adicionar outras.",
    },
    {
      id: "socialMedia",
      type: "array",
      label: "Redes sociais",
      maxItems: 5,
      noneOnlyFirstEntry: true,
      noneValue: "NONE",
      noneField: "platform",
      ds160List: "dtlSocial",
      fields: [
        {
          id: "platform",
          type: "select",
          label: "Plataforma",
          required: true,
          options: SOCIAL_PLATFORMS,
          default: "NONE",
        },
        {
          id: "handle",
          type: "text",
          label: "Identificador / Usuário",
          required: true,
          maxLen: 50,
          showWhen: { field: "platform", notIn: ["NONE"] },
        },
      ],
    },
    {
      id: "additionalSocialMedia",
      type: "radio",
      label: "Usou outros sites/apps sociais nos últimos 5 anos?",
      required: true,
      hint: "Não inclui mensagens privadas (ex: WhatsApp).",
      ds160: "rblAddSocial",
    },
    {
      id: "additionalSocialMediaAccounts",
      type: "array",
      label: "Outras redes sociais",
      maxItems: 4,
      showWhen: { field: "additionalSocialMedia", equals: "Y" },
      fields: [
        {
          id: "platform",
          type: "text",
          label: "Plataforma",
          required: true,
          maxLen: 40,
        },
        {
          id: "handle",
          type: "text",
          label: "Identificador",
          required: true,
          maxLen: 40,
        },
      ],
    },
  ],
};
