import type { FormSection } from "../primitives";

export const family2SpouseSection: FormSection = {
  id: "family2",
  label: "Família — Cônjuge / Parceiro(a)",
  showWhen: {
    section: "personal1",
    field: "maritalStatus",
    in: ["M", "C", "L", "U"],
  },
  fields: [
    {
      id: "spouseSurname",
      type: "text",
      label: "Sobrenome do Cônjuge",
      required: true,
      maxLen: 33,
      noSpecial: true,
    },
    {
      id: "spouseGivenName",
      type: "text",
      label: "Nome do Cônjuge",
      required: true,
      maxLen: 33,
      noSpecial: true,
    },
    {
      id: "spouseDob",
      type: "date",
      label: "Data de Nascimento",
      required: true,
      notFuture: true,
    },
    {
      id: "spouseNationality",
      type: "select",
      label: "Nacionalidade",
      required: true,
      optionsRef: "countries",
    },
    {
      id: "spouseCityOfBirth",
      type: "text",
      label: "Cidade de Nascimento",
      required: true,
      maxLen: 20,
      allowUnknown: true,
    },
    {
      id: "spouseCountryOfBirth",
      type: "select",
      label: "País de Nascimento",
      required: true,
      optionsRef: "countries",
    },
    {
      id: "spouseAddressType",
      type: "select",
      label: "Endereço do Cônjuge",
      required: true,
      options: [
        { value: "H", label: "Mesmo endereço residencial" },
        { value: "M", label: "Mesmo endereço para correspondência" },
        { value: "U", label: "Mesmo contato nos EUA" },
        { value: "D", label: "Desconhecido" },
        { value: "O", label: "Outro — especificar" },
      ],
    },
    {
      id: "spouseCountry",
      type: "select",
      label: "País",
      required: true,
      optionsRef: "countries",
      default: "BRZL",
      showWhen: { field: "spouseAddressType", equals: "O" },
    },
    {
      id: "spousePostalCode",
      type: "text",
      label: "CEP / Código Postal",
      required: true,
      maxLen: 10,
      allowNA: true,
      showWhen: { field: "spouseAddressType", equals: "O" },
    },
    {
      id: "spouseStreet1",
      type: "text",
      label: "Endereço — Linha 1",
      required: true,
      maxLen: 40,
      hint: "Sem caixa postal.",
      showWhen: { field: "spouseAddressType", equals: "O" },
    },
    {
      id: "spouseStreet2",
      type: "text",
      label: "Endereço — Linha 2",
      maxLen: 40,
      showWhen: { field: "spouseAddressType", equals: "O" },
    },
    {
      id: "spouseCity",
      type: "text",
      label: "Cidade",
      required: true,
      maxLen: 20,
      showWhen: { field: "spouseAddressType", equals: "O" },
    },
    {
      id: "spouseState",
      type: "text",
      label: "Estado / Província",
      required: true,
      maxLen: 20,
      allowNA: true,
      showWhen: { field: "spouseAddressType", equals: "O" },
    },
  ],
};
