import type { FormSection } from "../primitives";

const RELATIVE_SUBFIELDS = [
  {
    id: "givenName" as const,
    type: "text" as const,
    label: "Nome",
    required: true,
    maxLen: 33,
    noSpecial: true,
  },
  {
    id: "surname" as const,
    type: "text" as const,
    label: "Sobrenome",
    required: true,
    maxLen: 33,
    noSpecial: true,
  },
  {
    id: "type" as const,
    type: "select" as const,
    label: "Parentesco",
    required: true,
    optionsRef: "relativeTypes" as const,
  },
  {
    id: "status" as const,
    type: "select" as const,
    label: "Status migratório",
    required: true,
    optionsRef: "usStatus" as const,
  },
];

export const family1Section: FormSection = {
  id: "family1",
  label: "Família — Pais e parentes nos EUA",
  fields: [
    { id: "fatherHeading", type: "heading", label: "Pai" },
    {
      id: "fatherSurname",
      type: "text",
      label: "Sobrenome do Pai",
      required: true,
      maxLen: 33,
      noSpecial: true,
      allowUnknown: true,
    },
    {
      id: "fatherGivenName",
      type: "text",
      label: "Nome do Pai",
      required: true,
      maxLen: 33,
      noSpecial: true,
      allowUnknown: true,
    },
    {
      id: "fatherDob",
      type: "date",
      label: "Data de Nascimento do Pai",
      required: true,
      allowUnknown: true,
      hideWhenAllUnknown: ["fatherSurname", "fatherGivenName"],
    },
    {
      id: "fatherInUS",
      type: "radio",
      label: "Pai está nos EUA?",
      required: true,
      hideWhenAllUnknown: ["fatherSurname", "fatherGivenName"],
    },
    {
      id: "fatherUSStatus",
      type: "select",
      label: "Status do pai nos EUA",
      required: true,
      optionsRef: "usStatus",
      showWhen: { field: "fatherInUS", equals: "Y" },
    },

    { id: "motherHeading", type: "heading", label: "Mãe" },
    {
      id: "motherSurname",
      type: "text",
      label: "Sobrenome da Mãe",
      required: true,
      maxLen: 33,
      noSpecial: true,
      allowUnknown: true,
    },
    {
      id: "motherGivenName",
      type: "text",
      label: "Nome da Mãe",
      required: true,
      maxLen: 33,
      noSpecial: true,
      allowUnknown: true,
    },
    {
      id: "motherDob",
      type: "date",
      label: "Data de Nascimento da Mãe",
      required: true,
      allowUnknown: true,
      hideWhenAllUnknown: ["motherSurname", "motherGivenName"],
    },
    {
      id: "motherInUS",
      type: "radio",
      label: "Mãe está nos EUA?",
      required: true,
      hideWhenAllUnknown: ["motherSurname", "motherGivenName"],
    },
    {
      id: "motherUSStatus",
      type: "select",
      label: "Status da mãe nos EUA",
      required: true,
      optionsRef: "usStatus",
      showWhen: { field: "motherInUS", equals: "Y" },
    },

    { id: "relativesHeading", type: "heading", label: "Parentes nos EUA" },
    {
      id: "immediateRelativesInUS",
      type: "radio",
      label: "Tem parentes imediatos nos EUA?",
      required: true,
      hint: "Cônjuge, noivo(a), filho(a), irmão/irmã. Não inclui pais.",
      spaceBefore: 16,
    },
    {
      id: "otherRelativesInUS",
      type: "radio",
      label: "Tem outros parentes nos EUA?",
      required: true,
      showWhen: { field: "immediateRelativesInUS", equals: "N" },
      spaceBefore: 16,
    },
    {
      id: "relatives",
      type: "array",
      label: "Parentes imediatos nos EUA",
      maxItems: 5,
      showWhen: { field: "immediateRelativesInUS", equals: "Y" },
      fields: RELATIVE_SUBFIELDS,
    },
    {
      id: "otherRelatives",
      type: "array",
      label: "Outros parentes nos EUA",
      maxItems: 5,
      showWhen: { field: "otherRelativesInUS", equals: "Y" },
      fields: RELATIVE_SUBFIELDS,
    },
  ],
};
