import type { FormSection } from "../primitives";

export const passportSection: FormSection = {
  id: "passport",
  label: "Passaporte",
  fields: [
    {
      id: "type",
      type: "select",
      label: "Tipo de Passaporte",
      required: true,
      options: [
        { value: "R", label: "Regular" },
        { value: "D", label: "Diplomático" },
        { value: "O", label: "Oficial" },
        { value: "L", label: "Laissez-Passer" },
        { value: "OT", label: "Outro" },
      ],
    },
    {
      id: "typeExplanation",
      type: "textarea",
      label: "Explique o tipo",
      required: true,
      maxLen: 200,
      showWhen: { field: "type", equals: "OT" },
    },
    {
      id: "number",
      type: "text",
      label: "Número do Passaporte",
      required: true,
      maxLen: 20,
      hint: "Digite exatamente como está no passaporte.",
    },
    {
      id: "bookNumber",
      type: "text",
      label: "Número do Livro",
      required: true,
      maxLen: 20,
      allowNA: true,
      hint: "Localizado na contracapa. Marque N/A se não tiver.",
    },
    {
      id: "issuingCountry",
      type: "select",
      label: "País / Autoridade Emissora",
      required: true,
      optionsRef: "countries",
    },
    {
      id: "issuedCity",
      type: "text",
      label: "Cidade de Emissão",
      required: true,
      maxLen: 20,
      noSpecial: true,
    },
    {
      id: "issuedState",
      type: "text",
      label: "Estado / Província de Emissão",
      required: true,
      maxLen: 20,
      noSpecial: true,
    },
    {
      id: "issuedCountry",
      type: "select",
      label: "País/Região onde foi emitido",
      required: true,
      optionsRef: "countries",
      hint:
        "Local físico onde o passaporte foi emitido (pode diferir do país emissor).",
    },
    {
      id: "issuanceDate",
      type: "date",
      label: "Data de Emissão",
      required: true,
      notFuture: true,
    },
    {
      id: "expirationDate",
      type: "date",
      label: "Data de Expiração",
      required: true,
      allowNA: true,
      hint: "Marque N/A se não houver data de validade.",
    },
    {
      id: "lostOrStolen",
      type: "radio",
      label: "Perdeu ou teve passaporte roubado?",
      required: true,
      hint: "Inclui qualquer passaporte anterior.",
    },
    {
      id: "lostPassports",
      type: "array",
      label: "Passaportes perdidos / roubados",
      maxItems: 5,
      showWhen: { field: "lostOrStolen", equals: "Y" },
      fields: [
        {
          id: "number",
          type: "text",
          label: "Número",
          required: true,
          maxLen: 20,
        },
        {
          id: "country",
          type: "select",
          label: "País emissor",
          required: true,
          optionsRef: "countries",
        },
        {
          id: "explanation",
          type: "textarea",
          label: "Explique",
          required: true,
          maxLen: 200,
        },
      ],
    },
  ],
};
