import type { FormSection } from "../primitives";

export const personal2Section: FormSection = {
  id: "personal2",
  label: "Informações Pessoais 2",
  fields: [
    {
      id: "nationality",
      type: "select",
      label: "Nacionalidade",
      required: true,
      optionsRef: "countries",
      ds160: "ddlAPP_NATL",
    },
    {
      id: "otherNationality",
      type: "radio",
      label: "Possui outra nacionalidade?",
      required: true,
      hint:
        "Informe todas as nacionalidades que possui ou já possuiu, independentemente de renúncia formal.",
      ds160: "rblAPP_OTH_NATL_IND",
    },
    {
      id: "otherNationalities",
      type: "array",
      label: "Outras nacionalidades",
      maxItems: 5,
      showWhen: { field: "otherNationality", equals: "Y" },
      ds160List: "dtlOTHER_NATL",
      fields: [
        {
          id: "country",
          type: "select",
          label: "País",
          required: true,
          optionsRef: "countries",
          excludeField: "nationality",
          fullWidth: true,
        },
        {
          id: "hasPassport",
          type: "radio",
          label: "Possui passaporte desse país?",
          required: true,
          fullWidth: true,
        },
        {
          id: "passportNumber",
          type: "text",
          label: "Número do passaporte",
          required: true,
          maxLen: 20,
          showWhen: { field: "hasPassport", equals: "Y" },
        },
      ],
    },
    {
      id: "permanentResident",
      type: "radio",
      label: "É residente permanente de outro país?",
      required: true,
      hint: "Permissão sem limitação de tempo.",
      ds160: "rblPermResOtherCntryInd",
    },
    {
      id: "permanentResidentCountries",
      type: "array",
      label: "Países de residência permanente",
      maxItems: 5,
      showWhen: { field: "permanentResident", equals: "Y" },
      ds160List: "dtlOthPermResCntry",
      fields: [
        {
          id: "country",
          type: "select",
          label: "País",
          required: true,
          optionsRef: "countries",
          excludeField: "nationality",
        },
      ],
    },
    {
      id: "nationalId",
      type: "text",
      label: "Identidade Nacional / CPF",
      required: true,
      maxLen: 20,
      allowNA: true,
      hint:
        "Número único de identificação (ex: CPF para brasileiros). Marque \"Não se aplica\" se não possuir.",
      ds160: "tbxAPP_NATIONAL_ID",
    },
    {
      id: "ssn",
      type: "ssn",
      label: "SSN dos EUA",
      required: true,
      allowNA: true,
      hint: "Apenas se já possuiu. Formato: XXX-XX-XXXX.",
      ds160: "tbxAPP_SSN1/2/3",
    },
    {
      id: "taxId",
      type: "text",
      label: "Número de Contribuinte dos EUA",
      required: true,
      maxLen: 20,
      allowNA: true,
      hint: "ITIN/EIN.",
      ds160: "tbxAPP_TAX_ID",
    },
  ],
};
