import type { FormSection } from "../primitives";

export const personal1Section: FormSection = {
  id: "personal1",
  label: "Informações Pessoais 1",
  fields: [
    {
      id: "givenName",
      type: "text",
      label: "Nome",
      required: true,
      maxLen: 33,
      noSpecial: true,
      hint: "Use FNU se o passaporte não tiver nome próprio.",
      ds160: "tbxAPP_GIVEN_NAME",
    },
    {
      id: "surname",
      type: "text",
      label: "Sobrenome",
      required: true,
      maxLen: 33,
      noSpecial: true,
      hint: "Inclua todos os sobrenomes do passaporte.",
      ds160: "tbxAPP_SURNAME",
    },
    {
      id: "fullNameNative",
      type: "text",
      label: "Nome no alfabeto nativo",
      required: true,
      maxLen: 100,
      allowNA: true,
      hint: "Alfabeto do país de origem (caractere não-romano).",
      ds160: "tbxAPP_FULL_NAME_NATIVE",
    },
    {
      id: "otherNamesUsed",
      type: "radio",
      label: "Já usou outros nomes?",
      required: true,
      hint:
        "Inclui nome de solteiro(a), religioso, profissional, apelido ou qualquer outro pelo qual você é ou foi conhecido(a).",
      ds160: "rblOtherNames",
    },
    {
      id: "otherNames",
      type: "array",
      label: "Outros nomes",
      maxItems: 5,
      showWhen: { field: "otherNamesUsed", equals: "Y" },
      ds160List: "DListAlias",
      fields: [
        {
          id: "givenName",
          type: "text",
          label: "Nome",
          required: true,
          maxLen: 33,
          noSpecial: true,
        },
        {
          id: "surname",
          type: "text",
          label: "Sobrenome",
          required: true,
          maxLen: 33,
          noSpecial: true,
        },
      ],
    },
    {
      id: "telecode",
      type: "radio",
      label: "Possui telecode?",
      required: true,
      hint: "Códigos de 4 dígitos para alfabetos não-romanos.",
      ds160: "rblTelecodeQuestion",
    },
    {
      id: "telecodeGivenName",
      type: "text",
      label: "Telecode do Nome",
      required: true,
      maxLen: 20,
      groupLabel: "Resposta",
      showWhen: { field: "telecode", equals: "Y" },
      ds160: "tbxAPP_TelecodeGIVEN_NAME",
    },
    {
      id: "telecodeSurname",
      type: "text",
      label: "Telecode do Sobrenome",
      required: true,
      maxLen: 20,
      showWhen: { field: "telecode", equals: "Y" },
      ds160: "tbxAPP_TelecodeSURNAME",
    },
    {
      id: "sex",
      type: "select",
      label: "Sexo",
      required: true,
      options: [
        { value: "M", label: "Masculino" },
        { value: "F", label: "Feminino" },
      ],
      ds160: "ddlAPP_GENDER",
    },
    {
      id: "maritalStatus",
      type: "select",
      label: "Estado Civil",
      required: true,
      options: [
        { value: "M", label: "Casado(a)" },
        { value: "C", label: "União Estável" },
        { value: "P", label: "União Civil" },
        { value: "S", label: "Solteiro(a)" },
        { value: "W", label: "Viúvo(a)" },
        { value: "D", label: "Divorciado(a)" },
        { value: "L", label: "Separado(a) Legalmente" },
        { value: "O", label: "Outro" },
      ],
      ds160: "ddlAPP_MARITAL_STATUS",
    },
    {
      id: "otherMaritalStatusText",
      type: "textarea",
      label: "Especifique estado civil",
      required: true,
      maxLen: 200,
      showWhen: { field: "maritalStatus", equals: "O" },
      ds160: "tbxOtherMaritalStatus",
    },
    {
      id: "dob",
      type: "date",
      label: "Data de Nascimento",
      required: true,
      notFuture: true,
      hint: "DD-MMM-AAAA",
      ds160: "ddlDOBDay/Month / tbxDOBYear",
    },
    {
      id: "cityOfBirth",
      type: "text",
      label: "Cidade de Nascimento",
      required: true,
      maxLen: 20,
      noSpecial: true,
      ds160: "tbxAPP_POB_CITY",
    },
    {
      id: "stateOfBirth",
      type: "text",
      label: "Estado/Província de Nascimento",
      required: true,
      maxLen: 20,
      noSpecial: true,
      allowNA: true,
      ds160: "tbxAPP_POB_ST_PROVINCE",
    },
    {
      id: "countryOfBirth",
      type: "select",
      label: "País de Nascimento",
      required: true,
      optionsRef: "countries",
      default: "BRZL",
      hint:
        "Use o nome atualmente reconhecido para o local onde você nasceu (fronteiras podem ter mudado).",
      ds160: "ddlAPP_POB_CNTRY",
    },
  ],
};
