import type { FormSection } from "../primitives";

const LOS_UNITS = [
  { value: "Y", label: "Anos" },
  { value: "M", label: "Meses" },
  { value: "W", label: "Semanas" },
  { value: "D", label: "Dias" },
  { value: "H", label: "Menos de 24h" },
];

export const previousUSTravelSection: FormSection = {
  id: "previousUSTravel",
  label: "Viagens Anteriores aos EUA",
  fields: [
    {
      id: "hasBeenInUS",
      type: "radio",
      label: "Já esteve nos EUA?",
      required: true,
      hint: "Informe se já visitou os Estados Unidos em qualquer momento.",
    },
    {
      id: "previousVisits",
      type: "array",
      label: "Visitas anteriores",
      maxItems: 5,
      showWhen: { field: "hasBeenInUS", equals: "Y" },
      fields: [
        {
          id: "arrivalDate",
          type: "date",
          label: "Data de chegada",
          required: true,
          notFuture: true,
          fullWidth: true,
        },
        {
          id: "lengthOfStay",
          type: "text",
          label: "Tempo de permanência",
          required: true,
          maxLen: 3,
        },
        {
          id: "lengthOfStayUnit",
          type: "select",
          label: "Período",
          required: true,
          options: LOS_UNITS,
        },
      ],
    },
    {
      id: "hasDriversLicense",
      type: "radio",
      label: "Possui ou já possuiu CNH americana?",
      required: true,
      showWhen: { field: "hasBeenInUS", equals: "Y" },
    },
    {
      id: "driversLicenses",
      type: "array",
      label: "Carteiras de motorista americanas",
      maxItems: 5,
      showWhen: { field: "hasDriversLicense", equals: "Y" },
      fields: [
        {
          id: "number",
          type: "text",
          label: "Número da carteira",
          required: true,
          maxLen: 20,
          allowUnknown: true,
        },
        {
          id: "state",
          type: "select",
          label: "Estado emissor",
          required: true,
          optionsRef: "usStates",
        },
      ],
    },
    {
      id: "hasUSVisa",
      type: "radio",
      label: "Já recebeu visto americano?",
      required: true,
    },
    {
      id: "previousVisaIssueDate",
      type: "date",
      label: "Data de emissão do último visto",
      required: true,
      notFuture: true,
      showWhen: { field: "hasUSVisa", equals: "Y" },
    },
    {
      id: "previousVisaNumber",
      type: "text",
      label: "Número do visto",
      required: true,
      maxLen: 12,
      allowUnknown: true,
      hint: "8 dígitos em vermelho no visto.",
      showWhen: { field: "hasUSVisa", equals: "Y" },
    },
    {
      id: "sameVisaType",
      type: "radio",
      label: "Solicitando o mesmo tipo de visto?",
      required: true,
      showWhen: { field: "hasUSVisa", equals: "Y" },
    },
    {
      id: "sameCountry",
      type: "radio",
      label: "Solicitando no mesmo país onde emitido anteriormente?",
      required: true,
      showWhen: { field: "hasUSVisa", equals: "Y" },
    },
    {
      id: "tenPrint",
      type: "radio",
      label: "Forneceu impressões dos 10 dedos?",
      required: true,
      hint: "Todos os dedos das mãos.",
      showWhen: { field: "hasUSVisa", equals: "Y" },
    },
    {
      id: "visaLost",
      type: "radio",
      label: "Visto foi perdido ou roubado?",
      required: true,
      showWhen: { field: "hasUSVisa", equals: "Y" },
    },
    {
      id: "lostVisaYear",
      type: "text",
      label: "Ano da perda/roubo",
      required: true,
      maxLen: 4,
      showWhen: { field: "visaLost", equals: "Y" },
    },
    {
      id: "lostVisaExplanation",
      type: "textarea",
      label: "Explique a perda/roubo",
      required: true,
      maxLen: 4000,
      showWhen: { field: "visaLost", equals: "Y" },
    },
    {
      id: "visaCancelled",
      type: "radio",
      label: "Visto cancelado ou revogado?",
      required: true,
      showWhen: { field: "hasUSVisa", equals: "Y" },
    },
    {
      id: "cancelledExplanation",
      type: "textarea",
      label: "Explique o cancelamento",
      required: true,
      maxLen: 4000,
      showWhen: { field: "visaCancelled", equals: "Y" },
    },
    {
      id: "visaRefused",
      type: "radio",
      label: "Visto negado ou entrada recusada?",
      required: true,
      hint:
        "Inclui recusa de visto, recusa de admissão nos EUA e retirada voluntária de solicitação no porto de entrada.",
    },
    {
      id: "visaRefusedExplanation",
      type: "textarea",
      label: "Explique a recusa",
      required: true,
      maxLen: 4000,
      showWhen: { field: "visaRefused", equals: "Y" },
    },
    {
      id: "immigrantPetition",
      type: "radio",
      label: "Alguma petição de imigrante apresentada ao USCIS?",
      required: true,
    },
    {
      id: "immigrantPetitionExplanation",
      type: "textarea",
      label: "Explique a petição",
      required: true,
      maxLen: 4000,
      showWhen: { field: "immigrantPetition", equals: "Y" },
    },
    {
      id: "vwpDenial",
      type: "radio",
      label: "Entrada negada pelo Visa Waiver Program?",
      required: true,
      hint: "Apenas para países participantes do VWP.",
    },
    {
      id: "vwpDenialExplanation",
      type: "textarea",
      label: "Explique a negativa",
      required: true,
      maxLen: 4000,
      showWhen: { field: "vwpDenial", equals: "Y" },
    },
  ],
};
