import type { FormSection } from "../primitives";

const PURPOSE_CATEGORIES = [
  { value: "B", label: "Turismo / Negócios (B)" },
  { value: "F", label: "Estudante acadêmico (F)" },
  { value: "J", label: "Intercâmbio / J (Exchange)" },
  { value: "O", label: "Outros (O)" },
];

// Subset mínimo — purposeOfTrip é filteredBy purposeCategory.
const PURPOSE_OF_TRIP = [
  { value: "B1-B2", label: "B1/B2 — Turismo + Negócios", group: "B" },
  { value: "B1", label: "B1 — Negócios", group: "B" },
  { value: "B2", label: "B2 — Turismo", group: "B" },
  { value: "F1-F1", label: "F1 — Estudante acadêmico", group: "F" },
  { value: "F2-F2", label: "F2 — Dependente de F1", group: "F" },
  { value: "J1-J1", label: "J1 — Visitante de intercâmbio", group: "J" },
  { value: "J2-J2", label: "J2 — Dependente de J1", group: "J" },
  { value: "O1-O1", label: "O1 — Habilidade extraordinária", group: "O" },
  { value: "O2-O2", label: "O2 — Acompanhante de O1", group: "O" },
  { value: "O3-O3", label: "O3 — Dependente de O1/O2", group: "O" },
];

export const travelSection: FormSection = {
  id: "travel",
  label: "Viagem",
  fields: [
    {
      id: "purposeCategory",
      type: "select",
      label: "Categoria do Visto",
      required: true,
      options: PURPOSE_CATEGORIES,
      ds160: "ddlPurposeOfTrip",
    },
    {
      id: "purposeOfTrip",
      type: "select",
      label: "Tipo de Visto Específico",
      required: true,
      options: PURPOSE_OF_TRIP,
      filteredBy: { field: "purposeCategory" },
      ds160: "ddlOtherPurpose",
    },
    {
      id: "hasSpecificPlans",
      type: "radio",
      label: "Possui planos específicos de viagem?",
      required: true,
      hint: "Datas/voos/locais definidos → Sim. Apenas estimativa → Não.",
      ds160: "rblSpecificTravel",
    },

    // --- Bloco Y: planos específicos ---
    {
      id: "arrivalDate",
      type: "date",
      label: "Data de Chegada",
      required: true,
      showWhen: { field: "hasSpecificPlans", equals: "Y" },
      fullWidth: true,
    },
    {
      id: "arrivalFlight",
      type: "text",
      label: "Voo de Chegada",
      required: true,
      maxLen: 20,
      showWhen: { field: "hasSpecificPlans", equals: "Y" },
    },
    {
      id: "arrivalCity",
      type: "text",
      label: "Cidade de Chegada",
      required: true,
      maxLen: 20,
      showWhen: { field: "hasSpecificPlans", equals: "Y" },
    },
    {
      id: "departureDate",
      type: "date",
      label: "Data de Partida",
      required: true,
      showWhen: { field: "hasSpecificPlans", equals: "Y" },
    },
    {
      id: "departureFlight",
      type: "text",
      label: "Voo de Partida",
      required: true,
      maxLen: 20,
      showWhen: { field: "hasSpecificPlans", equals: "Y" },
    },
    {
      id: "departureCity",
      type: "text",
      label: "Cidade de Partida",
      required: true,
      maxLen: 20,
      showWhen: { field: "hasSpecificPlans", equals: "Y" },
    },
    {
      id: "specificLocations",
      type: "array",
      label: "Locais nos EUA",
      maxItems: 5,
      showWhen: { field: "hasSpecificPlans", equals: "Y" },
      fields: [
        {
          id: "location",
          type: "text",
          label: "Local",
          required: true,
          maxLen: 40,
        },
      ],
    },

    // --- Bloco N: estimativa ---
    {
      id: "nonSpecificArrival",
      type: "date",
      label: "Data prevista de chegada",
      required: true,
      showWhen: { field: "hasSpecificPlans", equals: "N" },
    },
    {
      id: "lengthOfStay",
      type: "text",
      label: "Tempo de permanência",
      required: true,
      maxLen: 3,
      showWhen: { field: "hasSpecificPlans", equals: "N" },
    },
    {
      id: "lengthOfStayUnit",
      type: "select",
      label: "Unidade",
      required: true,
      showWhen: { field: "hasSpecificPlans", equals: "N" },
      options: [
        { value: "Y", label: "Anos" },
        { value: "M", label: "Meses" },
        { value: "W", label: "Semanas" },
        { value: "D", label: "Dias" },
        { value: "H", label: "Menos de 24h" },
      ],
    },

    // --- Endereço nos EUA ---
    {
      id: "usAddressHeading",
      type: "heading",
      label: "Onde ficará hospedado nos EUA?",
    },
    {
      id: "usAddressStreet1",
      type: "text",
      label: "Endereço nos EUA — Linha 1",
      required: true,
      maxLen: 40,
    },
    {
      id: "usAddressStreet2",
      type: "text",
      label: "Endereço nos EUA — Linha 2",
      maxLen: 40,
    },
    {
      id: "usAddressCity",
      type: "text",
      label: "Cidade nos EUA",
      required: true,
      maxLen: 20,
    },
    {
      id: "usAddressState",
      type: "select",
      label: "Estado nos EUA",
      required: true,
      optionsRef: "usStates",
    },
    {
      id: "usAddressZip",
      type: "text",
      label: "CEP nos EUA",
      required: true,
      maxLen: 10,
    },

    // --- Pagamento ---
    {
      id: "whoIsPaying",
      type: "select",
      label: "Quem paga a viagem?",
      required: true,
      options: [
        { value: "S", label: "Eu mesmo" },
        { value: "O", label: "Outra pessoa" },
        { value: "P", label: "Empregador atual" },
        { value: "U", label: "Empregador nos EUA" },
        { value: "C", label: "Empresa / Organização" },
      ],
      ds160: "ddlWhoIsPaying",
    },

    // Bloco O: outra pessoa
    {
      id: "payerSurname",
      type: "text",
      label: "Sobrenome do pagador",
      required: true,
      maxLen: 33,
      noSpecial: true,
      showWhen: { field: "whoIsPaying", equals: "O" },
    },
    {
      id: "payerGivenName",
      type: "text",
      label: "Nome do pagador",
      required: true,
      maxLen: 33,
      noSpecial: true,
      showWhen: { field: "whoIsPaying", equals: "O" },
    },
    {
      id: "payerPhone",
      type: "phone",
      label: "Telefone do pagador",
      required: true,
      showWhen: { field: "whoIsPaying", equals: "O" },
    },
    {
      id: "payerEmail",
      type: "email",
      label: "Email do pagador",
      required: true,
      maxLen: 50,
      allowNA: true,
      showWhen: { field: "whoIsPaying", equals: "O" },
    },
    {
      id: "payerRelationship",
      type: "select",
      label: "Relação com o pagador",
      required: true,
      options: [
        { value: "C", label: "Filho/a" },
        { value: "P", label: "Pais" },
        { value: "S", label: "Cônjuge" },
        { value: "R", label: "Outro parente" },
        { value: "F", label: "Amigo" },
        { value: "O", label: "Outro" },
      ],
      showWhen: { field: "whoIsPaying", equals: "O" },
    },
    {
      id: "payerSameAddress",
      type: "radio",
      label: "Endereço do pagador = endereço residencial?",
      required: true,
      showWhen: { field: "whoIsPaying", equals: "O" },
    },
    {
      id: "payerPersonCountry",
      type: "select",
      label: "País do endereço do pagador",
      required: true,
      optionsRef: "countries",
      showWhen: { field: "payerSameAddress", equals: "N" },
    },
    {
      id: "payerPersonPostalCode",
      type: "text",
      label: "CEP / Código Postal do pagador",
      required: true,
      maxLen: 10,
      allowNA: true,
      showWhen: { field: "payerSameAddress", equals: "N" },
    },
    {
      id: "payerPersonStreet1",
      type: "text",
      label: "Endereço do pagador — Linha 1",
      required: true,
      maxLen: 40,
      showWhen: { field: "payerSameAddress", equals: "N" },
    },
    {
      id: "payerPersonStreet2",
      type: "text",
      label: "Endereço do pagador — Linha 2",
      maxLen: 40,
      showWhen: { field: "payerSameAddress", equals: "N" },
    },
    {
      id: "payerPersonCity",
      type: "text",
      label: "Cidade do pagador",
      required: true,
      maxLen: 20,
      showWhen: { field: "payerSameAddress", equals: "N" },
    },
    {
      id: "payerPersonState",
      type: "text",
      label: "Estado/Província do pagador",
      maxLen: 20,
      allowNA: true,
      showWhen: { field: "payerSameAddress", equals: "N" },
    },

    // Bloco C: empresa
    {
      id: "payerCompanyName",
      type: "text",
      label: "Nome da empresa pagadora",
      required: true,
      maxLen: 33,
      showWhen: { field: "whoIsPaying", equals: "C" },
    },
    {
      id: "payerCompanyPhone",
      type: "phone",
      label: "Telefone da empresa",
      required: true,
      showWhen: { field: "whoIsPaying", equals: "C" },
    },
    {
      id: "payerCompanyRelation",
      type: "text",
      label: "Relação com a empresa",
      required: true,
      maxLen: 40,
      showWhen: { field: "whoIsPaying", equals: "C" },
    },
    {
      id: "payerCoCountry",
      type: "select",
      label: "País da empresa pagadora",
      required: true,
      optionsRef: "countries",
      showWhen: { field: "whoIsPaying", equals: "C" },
    },
    {
      id: "payerCoPostalCode",
      type: "text",
      label: "CEP / Código Postal da empresa",
      required: true,
      maxLen: 10,
      allowNA: true,
      showWhen: { field: "whoIsPaying", equals: "C" },
    },
    {
      id: "payerCoStreet1",
      type: "text",
      label: "Endereço da empresa — Linha 1",
      required: true,
      maxLen: 40,
      showWhen: { field: "whoIsPaying", equals: "C" },
    },
    {
      id: "payerCoStreet2",
      type: "text",
      label: "Endereço da empresa — Linha 2",
      maxLen: 40,
      showWhen: { field: "whoIsPaying", equals: "C" },
    },
    {
      id: "payerCoCity",
      type: "text",
      label: "Cidade da empresa",
      required: true,
      maxLen: 20,
      showWhen: { field: "whoIsPaying", equals: "C" },
    },
    {
      id: "payerCoState",
      type: "text",
      label: "Estado/Província da empresa",
      maxLen: 20,
      allowNA: true,
      showWhen: { field: "whoIsPaying", equals: "C" },
    },
  ],
};
