import type { FormSection } from "../primitives";

export const workEducation3Section: FormSection = {
  id: "workEducation3",
  label: "Trabalho / Educação — Informações Adicionais",
  hideWhenMinor: true,
  fields: [
    {
      id: "clanTribe",
      type: "radio",
      label: "Pertence a algum clã ou tribo?",
      required: true,
    },
    {
      id: "clanTribeName",
      type: "text",
      label: "Nome do clã / tribo",
      required: true,
      maxLen: 80,
      showWhen: { field: "clanTribe", equals: "Y" },
    },
    {
      id: "languages",
      type: "array",
      label: "Idiomas que fala",
      maxItems: 5,
      fields: [
        { id: "name", type: "text", label: "Idioma", required: true, maxLen: 66 },
      ],
    },
    {
      id: "countriesVisited",
      type: "radio",
      label: "Visitou outros países nos últimos 5 anos?",
      required: true,
      hint: "Exceto os EUA (informados na seção anterior).",
    },
    {
      id: "countriesVisitedList",
      type: "array",
      label: "Países visitados",
      maxItems: 10,
      showWhen: { field: "countriesVisited", equals: "Y" },
      fields: [
        {
          id: "country",
          type: "select",
          label: "País / Região",
          required: true,
          optionsRef: "countries",
        },
      ],
    },
    {
      id: "organizationMember",
      type: "radio",
      label: "Pertenceu a organizações profissionais/sociais/caritativas?",
      required: true,
    },
    {
      id: "organizations",
      type: "array",
      label: "Organizações",
      maxItems: 5,
      showWhen: { field: "organizationMember", equals: "Y" },
      fields: [
        {
          id: "name",
          type: "text",
          label: "Nome da organização",
          required: true,
          maxLen: 66,
        },
      ],
    },
    {
      id: "specializedSkills",
      type: "radio",
      label: "Possui habilidades especializadas?",
      required: true,
      hint: "Armas, explosivos, nuclear/bio/química.",
    },
    {
      id: "specializedSkillsExplanation",
      type: "textarea",
      label: "Descreva as habilidades",
      required: true,
      maxLen: 4000,
      showWhen: { field: "specializedSkills", equals: "Y" },
    },
    {
      id: "militaryService",
      type: "radio",
      label: "Já serviu nas forças armadas?",
      required: true,
    },
    {
      id: "military",
      type: "array",
      label: "Serviço militar",
      maxItems: 5,
      showWhen: { field: "militaryService", equals: "Y" },
      fields: [
        {
          id: "country",
          type: "select",
          label: "País / Região",
          required: true,
          optionsRef: "countries",
        },
        {
          id: "branch",
          type: "text",
          label: "Ramo das forças armadas",
          required: true,
          maxLen: 40,
        },
        { id: "rank", type: "text", label: "Patente / Posto", required: true, maxLen: 40 },
        {
          id: "specialty",
          type: "text",
          label: "Especialidade militar",
          required: true,
          maxLen: 40,
        },
        {
          id: "startDate",
          type: "date",
          label: "Data início",
          required: true,
          notFuture: true,
        },
        {
          id: "endDate",
          type: "date",
          label: "Data término",
          required: true,
          notFuture: true,
        },
      ],
    },
    {
      id: "insurgentOrg",
      type: "radio",
      label: "Foi membro de organização insurgente/militante?",
      required: true,
    },
    {
      id: "insurgentOrgExplanation",
      type: "textarea",
      label: "Explique",
      required: true,
      maxLen: 4000,
      showWhen: { field: "insurgentOrg", equals: "Y" },
    },
  ],
};
