import type { FormSection } from "../primitives";

export const workEducation2Section: FormSection = {
  id: "workEducation2",
  label: "Trabalho / Educação — Anterior",
  hideWhenMinor: true,
  fields: [
    { id: "prevEmplHeading", type: "heading", label: "Empregos anteriores" },
    {
      id: "hasPreviousEmployment",
      type: "radio",
      label: "Já trabalhou anteriormente?",
      required: true,
    },
    {
      id: "previousEmployment",
      type: "array",
      label: "Empregos anteriores",
      maxItems: 5,
      showWhen: { field: "hasPreviousEmployment", equals: "Y" },
      fields: [
        { id: "name", type: "text", label: "Empregador", required: true, maxLen: 75 },
        {
          id: "prevEmplCountry",
          type: "select",
          label: "País / Região",
          required: true,
          optionsRef: "countries",
        },
        {
          id: "prevEmplPostalCode",
          type: "text",
          label: "CEP / Código Postal",
          maxLen: 10,
          allowNA: true,
        },
        {
          id: "prevEmplStreet1",
          type: "text",
          label: "Endereço — Linha 1",
          required: true,
          maxLen: 40,
        },
        {
          id: "prevEmplStreet2",
          type: "text",
          label: "Endereço — Linha 2",
          maxLen: 40,
        },
        {
          id: "prevEmplCity",
          type: "text",
          label: "Cidade",
          required: true,
          maxLen: 20,
        },
        {
          id: "prevEmplState",
          type: "text",
          label: "Estado / Província",
          maxLen: 20,
          allowNA: true,
        },
        { id: "prevEmplPhone", type: "phone", label: "Telefone" },
        { id: "jobTitle", type: "text", label: "Cargo", maxLen: 75 },
        {
          id: "supervisor",
          type: "text",
          label: "Supervisor (sobrenome)",
          maxLen: 33,
          allowNA: true,
        },
        {
          id: "supervisorGivenName",
          type: "text",
          label: "Supervisor (nome)",
          maxLen: 33,
          allowNA: true,
        },
        {
          id: "startDate",
          type: "date",
          label: "Data início",
          required: true,
          notFuture: true,
        },
        {
          id: "endDate",
          type: "date",
          label: "Data término",
          required: true,
          notFuture: true,
        },
        { id: "duties", type: "textarea", label: "Funções", maxLen: 4000 },
      ],
    },

    { id: "educationHeading", type: "heading", label: "Educação" },
    {
      id: "hasEducation",
      type: "radio",
      label: "Possui educação de nível médio/superior?",
      required: true,
    },
    {
      id: "education",
      type: "array",
      label: "Instituições de ensino",
      maxItems: 5,
      showWhen: { field: "hasEducation", equals: "Y" },
      fields: [
        { id: "name", type: "text", label: "Instituição", required: true, maxLen: 75 },
        {
          id: "schoolCountry",
          type: "select",
          label: "País / Região",
          required: true,
          optionsRef: "countries",
        },
        {
          id: "schoolPostalCode",
          type: "text",
          label: "CEP / Código Postal",
          maxLen: 10,
          allowNA: true,
        },
        {
          id: "schoolStreet1",
          type: "text",
          label: "Endereço — Linha 1",
          required: true,
          maxLen: 40,
        },
        {
          id: "schoolStreet2",
          type: "text",
          label: "Endereço — Linha 2",
          maxLen: 40,
        },
        {
          id: "schoolCity",
          type: "text",
          label: "Cidade",
          required: true,
          maxLen: 20,
        },
        {
          id: "schoolState",
          type: "text",
          label: "Estado / Província",
          maxLen: 20,
          allowNA: true,
        },
        { id: "course", type: "text", label: "Curso", required: true, maxLen: 66 },
        {
          id: "startDate",
          type: "date",
          label: "Data início",
          required: true,
          notFuture: true,
        },
        {
          id: "endDate",
          type: "date",
          label: "Data término",
          required: true,
          notFuture: true,
        },
      ],
    },
  ],
};
