import type { FormSection } from "../primitives";

export const workEducation1Section: FormSection = {
  id: "workEducation1",
  label: "Trabalho / Educação — Atual",
  hideWhenMinor: true,
  fields: [
    {
      id: "occupation",
      type: "select",
      label: "Ocupação / Profissão",
      required: true,
      optionsRef: "occupations",
      hint:
        "RT=Aposentado, HOME=Do Lar, UNEM=Desempregado dispensam bloco de empregador.",
    },
    {
      id: "otherOccupation",
      type: "textarea",
      label: "Especifique a ocupação",
      required: true,
      maxLen: 40,
      showWhen: { field: "occupation", equals: "OTHR" },
    },
    {
      id: "employerName",
      type: "text",
      label: "Nome do Empregador / Escola",
      required: true,
      maxLen: 75,
      showWhen: { field: "occupation", notIn: ["RETI", "HOME", "UNEM"] },
    },
    {
      id: "employerCountry",
      type: "select",
      label: "País / Região",
      required: true,
      optionsRef: "countries",
      showWhen: { field: "occupation", notIn: ["RETI", "HOME", "UNEM"] },
    },
    {
      id: "employerPostalCode",
      type: "text",
      label: "CEP / Código Postal",
      required: true,
      maxLen: 10,
      allowNA: true,
      showWhen: { field: "occupation", notIn: ["RETI", "HOME", "UNEM"] },
    },
    {
      id: "employerStreet1",
      type: "text",
      label: "Endereço — Linha 1",
      required: true,
      maxLen: 40,
      showWhen: { field: "occupation", notIn: ["RETI", "HOME", "UNEM"] },
    },
    {
      id: "employerStreet2",
      type: "text",
      label: "Endereço — Linha 2",
      maxLen: 40,
      showWhen: { field: "occupation", notIn: ["RETI", "HOME", "UNEM"] },
    },
    {
      id: "employerCity",
      type: "text",
      label: "Cidade",
      required: true,
      maxLen: 20,
      showWhen: { field: "occupation", notIn: ["RETI", "HOME", "UNEM"] },
    },
    {
      id: "employerState",
      type: "text",
      label: "Estado / Província",
      required: true,
      maxLen: 20,
      allowNA: true,
      showWhen: { field: "occupation", notIn: ["RETI", "HOME", "UNEM"] },
    },
    {
      id: "employerPhone",
      type: "phone",
      label: "Telefone",
      required: true,
      showWhen: { field: "occupation", notIn: ["RETI", "HOME", "UNEM"] },
    },
    {
      id: "employerStartDate",
      type: "date",
      label: "Data de início",
      required: true,
      notFuture: true,
      showWhen: { field: "occupation", notIn: ["RETI", "HOME", "UNEM"] },
    },
    {
      id: "monthlySalary",
      type: "text",
      label: "Salário mensal (R$)",
      required: true,
      maxLen: 15,
      showWhen: { field: "occupation", notIn: ["RETI", "HOME", "UNEM"] },
    },
    {
      id: "duties",
      type: "textarea",
      label: "Descrição das funções",
      required: true,
      maxLen: 4000,
      hint:
        "Forneça detalhes completos e honestos. Respostas vagas podem causar atrasos ou negativas.",
      showWhen: { field: "occupation", notIn: ["RETI", "HOME", "UNEM"] },
    },
  ],
};
